apiVersion: v1
kind: Service
metadata:
  name: nginx-web-nolb
  labels:
    app: nginx-web-nolb
spec:
  ports:
  - port: 5555
    targetPort: 80
  selector:
    app: nginx-web-nolb
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: nginx-web-nolb
  name: nginx-web-nolb
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx-web-nolb
      name: nginx-web-nolb
    spec:
      containers:
      - imagePullPolicy: IfNotPresent
        name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
          hostPort: 50000
          name: "http"