apiVersion: v1
kind: Service
metadata:
  name: win-webserver
  labels:
    app: win-webserver
spec:
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: 80
  selector:
    app: win-webserver
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: win-webserver
  labels:
    app: win-webserver
spec:
  template:
    metadata:
      labels:
        app: win-webserver
    spec:
      containers:
      - imagePullPolicy: IfNotPresent
        name: windowswebserver
        image: microsoft/iis
      - ports:
          name: "demo"
          protocol: tcp
        - hostPort: 4444
          containerPort: 80
      nodeSelector:
        beta.kubernetes.io/os: windows
